# Generated by Django 4.0 on 2021-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=10)),
                ('category', models.CharField(default='', max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('disc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='shop\\image')),
            ],
        ),
    ]
