# Generated by Django 4.0 on 2022-01-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disc',
            new_name='desc',
        ),
    ]
